project:
  type: book
  output-dir: docs

book:
  title: "Karte Hannover"
#  author: "Norah Jones"
  date: today
  favicon: ./images/favicon-32x32.png
  chapters:
    - index.ipynb
  repo-url: https://github.com/NFDI4Culture/KarteHannover
  repo-actions: [source]

format:
  html:
    toc: false
    number-sections: false
    theme: #see https://bootswatch.com/
      - united